// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCKuVA2Cy6E-eVygs4Znbd7Nr_GYNffgR8',
    appId: '1:973108526550:web:d365b74eb60d209328f877',
    messagingSenderId: '973108526550',
    projectId: 'carbon-shadow-tracker',
    authDomain: 'carbon-shadow-tracker.firebaseapp.com',
    storageBucket: 'carbon-shadow-tracker.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCy-FBKSub4EaMiIHQ2GbQPfH509kB7nUI',
    appId: '1:973108526550:android:df1b27f5dc47602628f877',
    messagingSenderId: '973108526550',
    projectId: 'carbon-shadow-tracker',
    storageBucket: 'carbon-shadow-tracker.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCKuVA2Cy6E-eVygs4Znbd7Nr_GYNffgR8',
    appId: '1:973108526550:web:2686f6c6c4f49a1b28f877',
    messagingSenderId: '973108526550',
    projectId: 'carbon-shadow-tracker',
    authDomain: 'carbon-shadow-tracker.firebaseapp.com',
    storageBucket: 'carbon-shadow-tracker.firebasestorage.app',
  );
}
